### ISSUE TITLE
马老师，你还好吧？

### ISSUE THREAD

**Issue by frank-pian** [caadxyz/micropolis#1]
失联有一阵子了，没出啥事吧

**Comment by mahaidong** [comment]
:（  滞留英国，飞机航班被取消两次。

**Comment by frank-pian** [comment]
> :（  滞留英国，飞机航班被取消两次。

哦哦，那还好，我还以为被隔离了……那马老师你注意防护
　　〇＿＿＿＿
　　 ||　　　　|
　　 ||！加油! |
　　 ||　　　　|
　　 ||￣￣￣￣
  ∧_∧||
(`･ω･||
（ つ||０
　uｰu
